name: Backpack
version: '1.0-SNAPSHOT'
main: de.schnorrenbergers.backpack.BackpackPlugin
api-version: '26.2'
commands:
  backpack:
    description: Öffnet den geteilten Rucksack deines Teams
    usage: /backpack [info]
    aliases: [bp]
