name: LobbyPlugin
version: '1.0-SNAPSHOT'
main: de.schnorrenbergers.lobby.LobbyPlugin
api-version: '26.2'
commands:
  servermanger:
    description: Server verwalten und neue Server erstellen
  warp:
    description: Auf einen anderen Server springen
    usage: /warp [server]
