name: LobbyPlugin
version: '1.0-SNAPSHOT'
main: de.schnorrenbergers.lobby.LobbyPlugin
api-version: '26.2'
commands:
  servermanger:
    description: Server verwalten und neue Server erstellen
    usage: /servermanger [create|stop|restart|list]
  warp:
    description: Auf einen anderen Server springen
    usage: /warp [server]
  events:
    description: Den Eventkalender öffnen
    usage: /events
  bwdebug:
    description: Eine Bedwars Runde starten und hinspringen
    usage: /bwdebug [list|stop <name>]
permissions:
  network.warp.always:
    description: Darf jeden Server jederzeit verlassen
    default: op
