name: Survival
version: '1.0-SNAPSHOT'
main: de.schnorrenbergers.survival.Survival
api-version: '26.2'
commands:
  debug:
  admin:
  cteam:
  rs:
  servermanger:
  shopkeeper:
  shop:
    description: Marktplatz öffnen oder einen Shop erstellen
    usage: /shop [create <name>]
  legitimize:
  events:
    description: Den Eventkalender öffnen
    usage: /events
  banane:
  warp:
    description: Auf einen anderen Server springen
    usage: /warp [server]
